services:
    # Data provider wrapper for retrieving data from the
    # video manager pro API
    data_providers.vmprosearch:
        class: MovingImage\DataProvider\VideoManagerProSearch
        arguments:
            - '@vmpro_api.client'